name: EnchantGUI
version: 1.0
main: com.Rayne.EnchantGUI.EnchantGUIPlugin
api-version: 1.20
description: A plugin to purchase and upgrade pickaxe enchantments via a GUI.
authors: "Rayne"
depend: [Vault]
